// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyNhanSuAPI.Data;

#nullable disable

namespace QuanLyNhanSuAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyNhanSuAPI.Models.HoSoNhanSu.DiemThanhCongCuaOkr", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("Diem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValueSql("((0.5))");

                    b.HasKey("Id")
                        .HasName("PK__DiemThan__3214EC0760339709");

                    b.ToTable("DiemThanhCongCuaOKR", (string)null);
                });

            modelBuilder.Entity("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbChucVu", b =>
                {
                    b.Property<int>("IdCv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdCV");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCv"));

                    b.Property<bool?>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("TenChucVu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdCv")
                        .HasName("PK__tb_ChucV__B7739095E99E25F7");

                    b.ToTable("tb_ChucVu", (string)null);
                });

            modelBuilder.Entity("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbDiNuocNgoai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdNv")
                        .HasColumnType("int")
                        .HasColumnName("IdNV");

                    b.Property<bool?>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("MucDich")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("NgayDi")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayVe")
                        .HasColumnType("date");

                    b.Property<string>("QuocGiaDen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ThoiGian")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__tb_DiNuo__3214EC0755D93C0E");

                    b.HasIndex("IdNv");

                    b.ToTable("tb_DiNuocNgoai", (string)null);
                });

            modelBuilder.Entity("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbHoSo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdNv")
                        .HasColumnType("int")
                        .HasColumnName("IdNV");

                    b.Property<bool?>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<bool?>("LoaiHoSo")
                        .HasColumnType("bit");

                    b.Property<string>("TapTin")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenHoSo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK__tb_HoSo__3214EC07FF9307C9");

                    b.HasIndex("IdNv");

                    b.ToTable("tb_HoSo", (string)null);
                });

            modelBuilder.Entity("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbKhenThuongKyLuat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CapQuyetDinh")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("DenNgay")
                        .HasColumnType("date");

                    b.Property<string>("DinhKem")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("HinhThuc")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("IdNv")
                        .HasColumnType("int")
                        .HasColumnName("IdNV");

                    b.Property<bool?>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<bool?>("Loai")
                        .HasColumnType("bit");

                    b.Property<string>("LyDo")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("NguoiKy")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SoQuyetDinh")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("TuNgay")
                        .HasColumnType("date");

                    b.HasKey("Id")
                        .HasName("PK__tb_KhenT__3214EC077E63EDDC");

                    b.HasIndex("IdNv");

                    b.ToTable("tb_KhenThuong_KyLuat", (string)null);
                });

            modelBuilder.Entity("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbLichSuBanThanNhanVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DenNgay")
                        .HasColumnType("date");

                    b.Property<int?>("IdNv")
                        .HasColumnType("int")
                        .HasColumnName("IdNV");

                    b.Property<bool?>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("LamGi")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Odau")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("ODau");

                    b.Property<DateTime?>("TuNgay")
                        .HasColumnType("date");

                    b.HasKey("Id")
                        .HasName("PK__tb_LichS__3214EC07273B86DB");

                    b.HasIndex("IdNv");

                    b.ToTable("tb_LichSuBanThanNhanVien", (string)null);
                });

            modelBuilder.Entity("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbOkr", b =>
                {
                    b.Property<int>("IdOkr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOkr"));

                    b.Property<string>("ChuSoHuu")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<double?>("Diem")
                        .HasColumnType("float");

                    b.Property<int?>("DiemThanhCong")
                        .HasColumnType("int");

                    b.Property<bool?>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<bool?>("KetQua")
                        .HasColumnType("bit");

                    b.Property<string>("KieuOkr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("LaKetQuaThenChot")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MucTieu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Nam")
                        .HasColumnType("date");

                    b.Property<int?>("NhanVien")
                        .HasColumnType("int");

                    b.Property<int?>("PhongBan")
                        .HasColumnType("int");

                    b.Property<string>("Quy")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("TrongSo")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("IdOkr")
                        .HasName("PK__tb_OKR__2A0B92DCF590D442");

                    b.HasIndex("DiemThanhCong");

                    b.HasIndex("LaKetQuaThenChot");

                    b.HasIndex("NhanVien");

                    b.HasIndex("PhongBan");

                    b.ToTable("tb_OKR", (string)null);
                });

            modelBuilder.Entity("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbPhongBan", b =>
                {
                    b.Property<int>("IdPb")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdPB");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPb"));

                    b.Property<bool?>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<int?>("PhongBanCapTren")
                        .HasColumnType("int");

                    b.Property<int?>("QuanLy")
                        .HasColumnType("int");

                    b.Property<string>("TenPhongBan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdPb")
                        .HasName("PK__tb_Phong__B7703B315BD0B293");

                    b.HasIndex("PhongBanCapTren");

                    b.HasIndex("QuanLy");

                    b.ToTable("tb_PhongBan", (string)null);
                });

            modelBuilder.Entity("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbQuaTrinhCongTac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChucDanh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("DangHoatDong")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DenNgay")
                        .HasColumnType("date");

                    b.Property<string>("FileQuyetDinh")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("IdNv")
                        .HasColumnType("int")
                        .HasColumnName("IdNV");

                    b.Property<bool?>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<bool?>("Loai")
                        .HasColumnType("bit");

                    b.Property<string>("LoaiHdld")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("LoaiHDLD");

                    b.Property<string>("LyDo")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("NgayHieuLuc")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayQuyetDinh")
                        .HasColumnType("date");

                    b.Property<string>("NguoiKy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoHdld")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SoHDLD");

                    b.Property<string>("SoQd")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SoQD");

                    b.Property<string>("TenCongTy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenDoi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenPhongBan")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("TuNgay")
                        .HasColumnType("date");

                    b.HasKey("Id")
                        .HasName("PK__tb_QuaTr__3214EC076769272D");

                    b.HasIndex("IdNv");

                    b.HasIndex(new[] { "SoQd" }, "UQ__tb_QuaTr__BC3C524B9779704C")
                        .IsUnique()
                        .HasFilter("[SoQD] IS NOT NULL");

                    b.ToTable("tb_QuaTrinhCongTac", (string)null);
                });

            modelBuilder.Entity("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbQuaTrinhDaoTao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BangCap")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CheDoHoc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ChuyenMon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DenNam")
                        .HasColumnType("date");

                    b.Property<int?>("IdNv")
                        .HasColumnType("int")
                        .HasColumnName("IdNV");

                    b.Property<bool?>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("KetQua")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LoaiDaoTao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NganhDaoTao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("NgayCap")
                        .HasColumnType("date");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("QuocGia")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("SoBang")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ThoiGian")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TruongDaoTao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("TuNam")
                        .HasColumnType("date");

                    b.HasKey("Id")
                        .HasName("PK__tb_QuaTr__3214EC07027CBA84");

                    b.HasIndex("IdNv");

                    b.ToTable("tb_QuaTrinhDaoTao", (string)null);
                });

            modelBuilder.Entity("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbQuaTrinhDaoTaoCuMoi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DangBang")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("HetHan")
                        .HasColumnType("date");

                    b.Property<string>("HinhThuc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("HoanTat")
                        .HasColumnType("bit");

                    b.Property<int?>("IdNv")
                        .HasColumnType("int")
                        .HasColumnName("IdNV");

                    b.Property<bool?>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("KhoaHoc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("LoaiDaoTao")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayCap")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("date");

                    b.Property<int?>("SoBang")
                        .HasColumnType("int");

                    b.Property<string>("SoQuyetDinh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenBang")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TruongDonVi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Truong_DonVi");

                    b.HasKey("Id")
                        .HasName("PK__tb_QuaTr__3214EC07151343B8");

                    b.HasIndex("IdNv");

                    b.ToTable("tb_QuaTrinhDaoTaoCuMoi", (string)null);
                });

            modelBuilder.Entity("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbQuaTrinhDaoTaoMoi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DangBang")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DiaDiem")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool?>("HetHan")
                        .HasColumnType("bit");

                    b.Property<string>("HinhThuc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("HoanTat")
                        .HasColumnType("bit");

                    b.Property<int?>("IdNv")
                        .HasColumnType("int")
                        .HasColumnName("IdNV");

                    b.Property<bool?>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("KetQua")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("KhoaHoc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayCap")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("date");

                    b.Property<int?>("SoBang")
                        .HasColumnType("int");

                    b.Property<string>("SoQuyetDinh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenBang")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TruongDonVi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Truong_DonVi");

                    b.HasKey("Id")
                        .HasName("PK__tb_QuaTr__3214EC07139862CA");

                    b.HasIndex("IdNv");

                    b.ToTable("tb_QuaTrinhDaoTaoMoi", (string)null);
                });

            modelBuilder.Entity("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbQuaTrinhLamViecCuaThanNhan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CapBac")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ChucVu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CongViec")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("DenNam")
                        .HasColumnType("date");

                    b.Property<string>("DonVi")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("IdThanNhan")
                        .HasColumnType("int");

                    b.Property<bool?>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("LoaiChucVu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("TrongNganh")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("TuNam")
                        .HasColumnType("date");

                    b.HasKey("Id")
                        .HasName("PK__tb_QuaTr__3214EC0768EF9789");

                    b.HasIndex("IdThanNhan");

                    b.ToTable("tb_QuaTrinhLamViecCuaThanNhan", (string)null);
                });

            modelBuilder.Entity("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbTaiKhoan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<int?>("IdNv")
                        .HasColumnType("int");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Role")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK__tb_TaiKh__3214EC0731F56160");

                    b.HasIndex("IdNv");

                    b.ToTable("tb_TaiKhoan", (string)null);
                });

            modelBuilder.Entity("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbThongTinChinhTri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CheDoHoc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DenNgay")
                        .HasColumnType("date");

                    b.Property<int?>("IdNv")
                        .HasColumnType("int");

                    b.Property<bool?>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<decimal?>("KinhPhi")
                        .HasColumnType("money");

                    b.Property<DateTime?>("NgayCap")
                        .HasColumnType("date");

                    b.Property<string>("NguonKinhPhi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrinhDoChinhTri")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("TuNgay")
                        .HasColumnType("date");

                    b.HasKey("Id")
                        .HasName("PK__tb_Thong__3214EC07AE914137");

                    b.HasIndex("IdNv");

                    b.ToTable("tb_ThongTinChinhTri", (string)null);
                });

            modelBuilder.Entity("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbThongTinDoanDang", b =>
                {
                    b.Property<int>("IdNv")
                        .HasColumnType("int")
                        .HasColumnName("IdNV");

                    b.Property<string>("ChucVu1")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ChucVu2")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("DaVaoDang")
                        .HasColumnType("bit");

                    b.Property<bool?>("DaVaoDoan")
                        .HasColumnType("bit");

                    b.Property<string>("DanhHieuDuocPhong")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DiaChi1")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("DiaChi2")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("NgayCapThe")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayChinhThuc1")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayChinhThuc2")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayNhapNgu")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayVaoDang1")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayVaoDang2")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayVaoDoan")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayXuatNgu")
                        .HasColumnType("date");

                    b.Property<string>("NguoiThuHai")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NguoiThuNhat")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("QuanHamChucVuCaoNhat")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("SoTheDang")
                        .HasColumnType("int");

                    b.Property<string>("SoTruong")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdNv")
                        .HasName("PK__tb_Thong__B773C9708379E3CA");

                    b.ToTable("tb_ThongTinDoanDang", (string)null);
                });

            modelBuilder.Entity("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbThongTinGiaDinh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("ConSong")
                        .HasColumnType("bit");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("IdNv")
                        .HasColumnType("int")
                        .HasColumnName("IdNV");

                    b.Property<bool?>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("Phuong")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("QuanHe")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("QuanHuyen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TinhThanh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__tb_Thong__3214EC07F706D245");

                    b.HasIndex("IdNv");

                    b.ToTable("tb_ThongTinGiaDinh", (string)null);
                });

            modelBuilder.Entity("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbThongTinHopDongLaoDong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("BacLuong")
                        .HasColumnType("float");

                    b.Property<string>("ChucDanh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FileHdld")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("FileHDLD");

                    b.Property<string>("FileQuyetDinh")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double?>("HeSoLuong")
                        .HasColumnType("float");

                    b.Property<int?>("IdNv")
                        .HasColumnType("int")
                        .HasColumnName("IdNV");

                    b.Property<bool?>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("LoaiHopDong")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("NgayChinhThuc")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayGiaHan")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayHetHan")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayKy")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayThuViec")
                        .HasColumnType("date");

                    b.Property<string>("NguoiKy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoHdld")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("SoHDLD");

                    b.Property<string>("ThoiHan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__tb_Thong__3214EC076A9523FC");

                    b.HasIndex("IdNv");

                    b.HasIndex(new[] { "SoHdld" }, "UQ__tb_Thong__062764664F071968")
                        .IsUnique()
                        .HasFilter("[SoHDLD] IS NOT NULL");

                    b.ToTable("tb_ThongTinHopDongLaoDong", (string)null);
                });

            modelBuilder.Entity("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbThongTinNgoaiNgu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BangCap")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("ChinhPhu")
                        .HasColumnType("bit");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("IdNv")
                        .HasColumnType("int")
                        .HasColumnName("IdNV");

                    b.Property<bool?>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("KetQua")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("KinhPhi")
                        .HasColumnType("money");

                    b.Property<DateTime?>("NgayCap")
                        .HasColumnType("date");

                    b.Property<string>("NgoaiNgu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NguonKinhPhi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__tb_Thong__3214EC0751591164");

                    b.HasIndex("IdNv");

                    b.ToTable("tb_ThongTinNgoaiNgu", (string)null);
                });

            modelBuilder.Entity("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbThongTinNhanVien", b =>
                {
                    b.Property<int>("IdNv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdNV");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNv"));

                    b.Property<double?>("BacLuong")
                        .HasColumnType("float");

                    b.Property<string>("BiDanh")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("ChieuCao")
                        .HasColumnType("int");

                    b.Property<string>("Cmnd")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CMND");

                    b.Property<string>("DanToc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DiaChiTamTru")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("DiaChiThuongTru")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("DienThoaiNha")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Dtdd")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("DTDD");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("HoKhaiSinh")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("HoThuongDung")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("IdCv")
                        .HasColumnType("int")
                        .HasColumnName("IdCV");

                    b.Property<int?>("IdPb")
                        .HasColumnType("int")
                        .HasColumnName("IdPB");

                    b.Property<bool?>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("LyDoNghiViec")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("MoTaCongViec")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("NgayCapCmnd")
                        .HasColumnType("date")
                        .HasColumnName("NgayCapCMND");

                    b.Property<DateTime?>("NgayCapHoChieu")
                        .HasColumnType("date");

                    b.Property<DateTime>("NgayCapTheCanCuoc")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayNghiViec")
                        .HasColumnType("date");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("NhanDang")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NoiCapCmnd")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("NoiCapCMND");

                    b.Property<string>("PhuongXaTamTru")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PhuongXaThuongTru")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("QuanHuyenTamTru")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("QuanHuyenThuongTru")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("QueQuanPhuongXa")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("QueQuanQuanHuyen")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("QueQuanThanhPho")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("QuocTich")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoHoChieu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenChucDanh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenKhaiSinh")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("TenThuongDung")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ThanhPhanGiaDinh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ThanhPhoTamTru")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ThanhPhoThuongTru")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TheCanCuoc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TonGiao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdNv")
                        .HasName("PK__tb_Thong__B773C970CE603B85");

                    b.HasIndex("IdCv");

                    b.HasIndex("IdPb");

                    b.ToTable("tb_ThongTinNhanVien", (string)null);
                });

            modelBuilder.Entity("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbThongTinViTinh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BangCap")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CheDoHoc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("Denngay")
                        .HasColumnType("date");

                    b.Property<int?>("IdNv")
                        .HasColumnType("int")
                        .HasColumnName("IdNV");

                    b.Property<bool?>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<decimal?>("KinhPhi")
                        .HasColumnType("money");

                    b.Property<DateTime?>("NgayCap")
                        .HasColumnType("date");

                    b.Property<string>("NguonKinhPhi")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("SoBang")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("TuNgay")
                        .HasColumnType("date");

                    b.HasKey("Id")
                        .HasName("PK__tb_Thong__3214EC072EE3659B");

                    b.HasIndex("IdNv");

                    b.ToTable("tb_ThongTinViTinh", (string)null);
                });

            modelBuilder.Entity("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbDiNuocNgoai", b =>
                {
                    b.HasOne("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbThongTinNhanVien", "IdNvNavigation")
                        .WithMany("TbDiNuocNgoais")
                        .HasForeignKey("IdNv")
                        .HasConstraintName("FK__tb_DiNuocN__IdNV__619B8048");

                    b.Navigation("IdNvNavigation");
                });

            modelBuilder.Entity("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbHoSo", b =>
                {
                    b.HasOne("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbThongTinNhanVien", "IdNvNavigation")
                        .WithMany("TbHoSos")
                        .HasForeignKey("IdNv")
                        .HasConstraintName("FK__tb_HoSo__IdNV__76969D2E");

                    b.Navigation("IdNvNavigation");
                });

            modelBuilder.Entity("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbKhenThuongKyLuat", b =>
                {
                    b.HasOne("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbThongTinNhanVien", "IdNvNavigation")
                        .WithMany("TbKhenThuongKyLuats")
                        .HasForeignKey("IdNv")
                        .HasConstraintName("FK__tb_KhenThu__IdNV__73BA3083");

                    b.Navigation("IdNvNavigation");
                });

            modelBuilder.Entity("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbLichSuBanThanNhanVien", b =>
                {
                    b.HasOne("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbThongTinNhanVien", "IdNvNavigation")
                        .WithMany("TbLichSuBanThanNhanViens")
                        .HasForeignKey("IdNv")
                        .HasConstraintName("FK__tb_LichSuB__IdNV__7F2BE32F");

                    b.Navigation("IdNvNavigation");
                });

            modelBuilder.Entity("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbOkr", b =>
                {
                    b.HasOne("QuanLyNhanSuAPI.Models.HoSoNhanSu.DiemThanhCongCuaOkr", "DiemThanhCongNavigation")
                        .WithMany("TbOkrs")
                        .HasForeignKey("DiemThanhCong")
                        .HasConstraintName("FK__tb_OKR__DiemThan__6DCC4D03");

                    b.HasOne("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbOkr", "LaKetQuaThenChotNavigation")
                        .WithMany("InverseLaKetQuaThenChotNavigation")
                        .HasForeignKey("LaKetQuaThenChot")
                        .HasConstraintName("FK__tb_OKR__LaKetQua__6AEFE058");

                    b.HasOne("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbThongTinNhanVien", "NhanVienNavigation")
                        .WithMany("TbOkrs")
                        .HasForeignKey("NhanVien")
                        .HasConstraintName("FK__tb_OKR__NhanVien__6CD828CA");

                    b.HasOne("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbPhongBan", "PhongBanNavigation")
                        .WithMany("TbOkrs")
                        .HasForeignKey("PhongBan")
                        .HasConstraintName("FK__tb_OKR__PhongBan__6BE40491");

                    b.Navigation("DiemThanhCongNavigation");

                    b.Navigation("LaKetQuaThenChotNavigation");

                    b.Navigation("NhanVienNavigation");

                    b.Navigation("PhongBanNavigation");
                });

            modelBuilder.Entity("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbPhongBan", b =>
                {
                    b.HasOne("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbPhongBan", "PhongBanCapTrenNavigation")
                        .WithMany("InversePhongBanCapTrenNavigation")
                        .HasForeignKey("PhongBanCapTren")
                        .HasConstraintName("FK__tb_PhongB__Phong__6166761E");

                    b.HasOne("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbThongTinNhanVien", "QuanLyNavigation")
                        .WithMany("TbPhongBans")
                        .HasForeignKey("QuanLy")
                        .HasConstraintName("FK__tb_PhongB__QuanL__607251E5");

                    b.Navigation("PhongBanCapTrenNavigation");

                    b.Navigation("QuanLyNavigation");
                });

            modelBuilder.Entity("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbQuaTrinhCongTac", b =>
                {
                    b.HasOne("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbThongTinNhanVien", "IdNvNavigation")
                        .WithMany("TbQuaTrinhCongTacs")
                        .HasForeignKey("IdNv")
                        .HasConstraintName("FK__tb_QuaTrin__IdNV__17036CC0");

                    b.Navigation("IdNvNavigation");
                });

            modelBuilder.Entity("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbQuaTrinhDaoTao", b =>
                {
                    b.HasOne("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbThongTinNhanVien", "IdNvNavigation")
                        .WithMany("TbQuaTrinhDaoTaos")
                        .HasForeignKey("IdNv")
                        .HasConstraintName("FK__tb_QuaTrin__IdNV__3E52440B");

                    b.Navigation("IdNvNavigation");
                });

            modelBuilder.Entity("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbQuaTrinhDaoTaoCuMoi", b =>
                {
                    b.HasOne("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbThongTinNhanVien", "IdNvNavigation")
                        .WithMany("TbQuaTrinhDaoTaoCuMois")
                        .HasForeignKey("IdNv")
                        .HasConstraintName("FK__tb_QuaTrin__IdNV__4F47C5E3");

                    b.Navigation("IdNvNavigation");
                });

            modelBuilder.Entity("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbQuaTrinhDaoTaoMoi", b =>
                {
                    b.HasOne("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbThongTinNhanVien", "IdNvNavigation")
                        .WithMany("TbQuaTrinhDaoTaoMois")
                        .HasForeignKey("IdNv")
                        .HasConstraintName("FK__tb_QuaTrin__IdNV__6754599E");

                    b.Navigation("IdNvNavigation");
                });

            modelBuilder.Entity("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbQuaTrinhLamViecCuaThanNhan", b =>
                {
                    b.HasOne("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbThongTinGiaDinh", "IdThanNhanNavigation")
                        .WithMany("TbQuaTrinhLamViecCuaThanNhans")
                        .HasForeignKey("IdThanNhan")
                        .HasConstraintName("FK__tb_QuaTri__IdTha__7C4F7684");

                    b.Navigation("IdThanNhanNavigation");
                });

            modelBuilder.Entity("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbTaiKhoan", b =>
                {
                    b.HasOne("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbThongTinNhanVien", "IdNvNavigation")
                        .WithMany("TbTaiKhoans")
                        .HasForeignKey("IdNv")
                        .HasConstraintName("FK__tb_TaiKhoa__IdNv__681373AD");

                    b.Navigation("IdNvNavigation");
                });

            modelBuilder.Entity("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbThongTinChinhTri", b =>
                {
                    b.HasOne("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbThongTinNhanVien", "IdNvNavigation")
                        .WithMany("TbThongTinChinhTris")
                        .HasForeignKey("IdNv")
                        .HasConstraintName("FK__tb_ThongTi__IdNv__4F7CD00D");

                    b.Navigation("IdNvNavigation");
                });

            modelBuilder.Entity("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbThongTinDoanDang", b =>
                {
                    b.HasOne("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbThongTinNhanVien", "IdNvNavigation")
                        .WithOne("TbThongTinDoanDang")
                        .HasForeignKey("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbThongTinDoanDang", "IdNv")
                        .IsRequired()
                        .HasConstraintName("FK__tb_ThongTi__IdNV__29221CFB");

                    b.Navigation("IdNvNavigation");
                });

            modelBuilder.Entity("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbThongTinGiaDinh", b =>
                {
                    b.HasOne("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbThongTinNhanVien", "IdNvNavigation")
                        .WithMany("TbThongTinGiaDinhs")
                        .HasForeignKey("IdNv")
                        .HasConstraintName("FK__tb_ThongTi__IdNV__797309D9");

                    b.Navigation("IdNvNavigation");
                });

            modelBuilder.Entity("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbThongTinHopDongLaoDong", b =>
                {
                    b.HasOne("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbThongTinNhanVien", "IdNvNavigation")
                        .WithMany("TbThongTinHopDongLaoDongs")
                        .HasForeignKey("IdNv")
                        .HasConstraintName("FK__tb_ThongTi__IdNV__02FC7413");

                    b.Navigation("IdNvNavigation");
                });

            modelBuilder.Entity("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbThongTinNgoaiNgu", b =>
                {
                    b.HasOne("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbThongTinNhanVien", "IdNvNavigation")
                        .WithMany("TbThongTinNgoaiNgus")
                        .HasForeignKey("IdNv")
                        .HasConstraintName("FK__tb_ThongTi__IdNV__49C3F6B7");

                    b.Navigation("IdNvNavigation");
                });

            modelBuilder.Entity("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbThongTinNhanVien", b =>
                {
                    b.HasOne("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbChucVu", "IdCvNavigation")
                        .WithMany("TbThongTinNhanViens")
                        .HasForeignKey("IdCv")
                        .HasConstraintName("FK__tb_ThongTi__IdCV__3B75D760");

                    b.HasOne("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbPhongBan", "IdPbNavigation")
                        .WithMany("TbThongTinNhanViens")
                        .HasForeignKey("IdPb")
                        .HasConstraintName("FK__tb_ThongTi__IdPB__3A81B327");

                    b.Navigation("IdCvNavigation");

                    b.Navigation("IdPbNavigation");
                });

            modelBuilder.Entity("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbThongTinViTinh", b =>
                {
                    b.HasOne("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbThongTinNhanVien", "IdNvNavigation")
                        .WithMany("TbThongTinViTinhs")
                        .HasForeignKey("IdNv")
                        .HasConstraintName("FK__tb_ThongTi__IdNV__4CA06362");

                    b.Navigation("IdNvNavigation");
                });

            modelBuilder.Entity("QuanLyNhanSuAPI.Models.HoSoNhanSu.DiemThanhCongCuaOkr", b =>
                {
                    b.Navigation("TbOkrs");
                });

            modelBuilder.Entity("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbChucVu", b =>
                {
                    b.Navigation("TbThongTinNhanViens");
                });

            modelBuilder.Entity("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbOkr", b =>
                {
                    b.Navigation("InverseLaKetQuaThenChotNavigation");
                });

            modelBuilder.Entity("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbPhongBan", b =>
                {
                    b.Navigation("InversePhongBanCapTrenNavigation");

                    b.Navigation("TbOkrs");

                    b.Navigation("TbThongTinNhanViens");
                });

            modelBuilder.Entity("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbThongTinGiaDinh", b =>
                {
                    b.Navigation("TbQuaTrinhLamViecCuaThanNhans");
                });

            modelBuilder.Entity("QuanLyNhanSuAPI.Models.HoSoNhanSu.TbThongTinNhanVien", b =>
                {
                    b.Navigation("TbDiNuocNgoais");

                    b.Navigation("TbHoSos");

                    b.Navigation("TbKhenThuongKyLuats");

                    b.Navigation("TbLichSuBanThanNhanViens");

                    b.Navigation("TbOkrs");

                    b.Navigation("TbPhongBans");

                    b.Navigation("TbQuaTrinhCongTacs");

                    b.Navigation("TbQuaTrinhDaoTaoCuMois");

                    b.Navigation("TbQuaTrinhDaoTaoMois");

                    b.Navigation("TbQuaTrinhDaoTaos");

                    b.Navigation("TbTaiKhoans");

                    b.Navigation("TbThongTinChinhTris");

                    b.Navigation("TbThongTinDoanDang");

                    b.Navigation("TbThongTinGiaDinhs");

                    b.Navigation("TbThongTinHopDongLaoDongs");

                    b.Navigation("TbThongTinNgoaiNgus");

                    b.Navigation("TbThongTinViTinhs");
                });
#pragma warning restore 612, 618
        }
    }
}
